### ISSUE TITLE
'r' is uninitialized in distrib/ulibc/src/stdlib/div.c

### ISSUE THREAD

**Issue by stepcity** [NewbiZ/xv6#20]
This could just be an issue with my compiler but I figured I'd make an issue anyways.
When running 'make', everything builds fine except for div.c. It fails with the following error:
```
src/stdlib/div.c: In function ‘div’:
src/stdlib/div.c:10:10: error: ‘r’ is used uninitialized in this function [-Werror=uninitialized]
   return r;
          ^
cc1: all warnings being treated as errors
```
I am using Debian 10 with Linux 4.4.0 and GCC 8.3.0 from the default repositories. Any help would be appreciated because this looks like it could be a very fun OS to play with.

**Comment by NewbiZ** [comment]
Thanks for the report. 
I did not try to build xv6 on such a recent gcc. Let me have a look tomorrow to see if I can fix this quickly.

**Comment by NewbiZ** [comment]
I had a look and the warning is indeed true. These parts of the ulibc are not implemented yet.
As a temporary fix, I suggest you replace line 8 from `div_t r;` to `div_t r = {0};` in `distrib/ulibc/src/stdlib/div.c` and `distrib/ulibc/src/stdlib/ldiv.c`.
That should allow you to build the project correctly (tested with gcc 9.3.0).

I will soon push a fix to correct these mistakes.

As an additional note, you may also have to change `QEMU = qemu` to `QEMU = qemu-system-x86_64` in `Makefile.common` if working with a modern qemu installation (at least that's the case on my Debian).
This will allow you to run the OS with `make qemu` after the build.
